# Generated by Django 2.2.6 on 2019-10-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=150)),
                ('pagar_em', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rendimentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=150)),
                ('pagar_em', models.DateTimeField()),
            ],
        ),
    ]
