# Generated by Django 2.2.6 on 2019-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191004_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='valores',
            name='parcelas_pagas',
            field=models.IntegerField(default=1),
        ),
    ]
